query ($id: ID) {
  players(where: {id: $id}) {
    status
    updatedAt
    createdAt
    id
    playerName
    playerRole
    playerImage {
      status
      updatedAt
      createdAt
      id
      handle
      fileName
      height
      width
      size
      mimeType
    }
    homePage {
      id
    }
  }
}
